version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: apps/backend/Dockerfile
    ports:
      - '3333:3000' # Maps localhost:3333 -> Container:3000
    env_file:
      - apps/backend/.env # Loads env from backend folder
    environment:
      - NODE_ENV=production
      - PORT=3000
    restart: unless-stopped
    # Optional: If you want to see logs immediately
    # tty: true
